version: "3.9"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      DYNAMIC_CONFIG_ENABLED: 'true'

  order-creation-service:
    depends_on:
      - kafka
    build: order-creation-service
    ports:
      - "8082:8082"

  order-export-marker-service:
    depends_on:
      - kafka
    build: order-export-marker-service
    ports:
      - "8083:8083"



#  zipkin:
#    image: java:openjdk-8u91-jdk
#    working_dir: /app
#    volumes:
#      - ./zipkin-server/build/libs:/app
#    command: java -jar /app/zipkin-server.jar --server.port=9411
#    links:
#      - rabbitmq
#    ports:
#      - "9411:9411"
#    environment:
#      RABBIT_HOST: rabbitmq
